# Linear Regression

Import required packages

In [192]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sb
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


Load and Profile the Data

In [193]:
fuelData = pd.read_csv("FuelConsumptionCo2.csv")
print(fuelData.dtypes)
print(fuelData.isna().values.any())

MODELYEAR                     int64
MAKE                         object
MODEL                        object
VEHICLECLASS                 object
ENGINESIZE                  float64
CYLINDERS                     int64
TRANSMISSION                 object
FUELTYPE                     object
FUELCONSUMPTION_CITY        float64
FUELCONSUMPTION_HWY         float64
FUELCONSUMPTION_COMB        float64
FUELCONSUMPTION_COMB_MPG      int64
CO2EMISSIONS                  int64
dtype: object
False


Create new Data Frame with selected Features

In [194]:
newFuelData = fuelData[["CYLINDERS", "ENGINESIZE", "CO2EMISSIONS", "FUELCONSUMPTION_COMB", "FUELCONSUMPTION_CITY", "FUELCONSUMPTION_HWY", "FUELCONSUMPTION_COMB_MPG"]]
print(newFuelData.head())

   CYLINDERS  ENGINESIZE  CO2EMISSIONS  FUELCONSUMPTION_COMB  \
0          4         2.0           196                   8.5   
1          4         2.4           221                   9.6   
2          4         1.5           136                   5.9   
3          6         3.5           255                  11.1   
4          6         3.5           244                  10.6   

   FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB_MPG  
0                   9.9                  6.7                        33  
1                  11.2                  7.7                        29  
2                   6.0                  5.8                        48  
3                  12.7                  9.1                        25  
4                  12.1                  8.7                        27  


Train the data using linear regression

In [195]:
train, test = train_test_split(newFuelData, test_size=0.2)
regression = linear_model.LinearRegression()
regression.fit(train[["ENGINESIZE"]], train[["CO2EMISSIONS"]])
print('Coefficients: ', regression.coef_)
print('Intercept: ',regression.intercept_)

Coefficients:  [[39.203]]
Intercept:  [124.569]


Evaluate the model

In [196]:
prediction = regression.predict(test[["ENGINESIZE"]])
for i in range(len(test)):
  print(test[["ENGINESIZE"]].values[i], prediction[i])

print("MAE : ", mean_absolute_error(test[["CO2EMISSIONS"]], prediction))
print("MSE : ", mean_squared_error(test[["CO2EMISSIONS"]], prediction))
print("R2 : ", r2_score(test[["CO2EMISSIONS"]], prediction))


[3.6] [265.7]
[2.4] [218.657]
[3.8] [273.541]
[2.4] [218.657]
[3.2] [250.019]
[3.5] [261.78]
[2.] [202.975]
[5.3] [332.346]
[1.4] [179.453]
[3.2] [250.019]
[2.] [202.975]
[3.] [242.179]
[5.3] [332.346]
[3.6] [265.7]
[3.7] [269.621]
[4.6] [304.904]
[1.6] [187.294]
[2.5] [222.577]
[6.2] [367.629]
[2.] [202.975]
[2.4] [218.657]
[4.7] [308.824]
[5.3] [332.346]
[2.] [202.975]
[4.7] [308.824]
[3.6] [265.7]
[3.2] [250.019]
[4.4] [297.063]
[2.] [202.975]
[3.] [242.179]
[2.] [202.975]
[5.3] [332.346]
[3.4] [257.86]
[2.5] [222.577]
[3.5] [261.78]
[8.4] [453.876]
[3.] [242.179]
[5.7] [348.027]
[2.5] [222.577]
[3.6] [265.7]
[1.8] [195.135]
[2.] [202.975]
[2.] [202.975]
[3.6] [265.7]
[3.7] [269.621]
[4.] [281.382]
[3.6] [265.7]
[2.5] [222.577]
[3.] [242.179]
[1.6] [187.294]
[1.8] [195.135]
[3.2] [250.019]
[2.5] [222.577]
[6.2] [367.629]
[6.2] [367.629]
[3.7] [269.621]
[1.4] [179.453]
[5.] [320.585]
[1.6] [187.294]
[3.] [242.179]
[4.8] [312.744]
[3.6] [265.7]
[6.4] [375.469]
[6.2] [367.629]
[1.6] [1

# Classification - KNN

Import all required packages

In [197]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


Load & profile the data

In [198]:
dataTitanic = pd.read_csv("titanic_train.csv")

for i in dataTitanic:
  print(i, dataTitanic[i].dtypes)
  if dataTitanic[i].isna().values.any() and dataTitanic[i].dtypes != object:
      dataTitanic[i] = dataTitanic[i].fillna(dataTitanic[i].mean())

train, test = train_test_split(dataTitanic, test_size=0.2)


passenger_id int64
pclass int64
name object
sex object
age float64
sibsp int64
parch int64
ticket object
fare float64
cabin object
embarked object
boat object
body float64
home.dest object
survived int64


Training Proces

In [199]:
KNN = KNeighborsClassifier(n_neighbors = 3).fit(train[["age", "fare"]], train["survived"])

Clasify new data & evaluate the model

In [200]:
newClassification = KNN.predict([[17,8],[8,10]])
print(newClassification)

classification = KNN.predict(test[["age", "fare"]])
accuracy = accuracy_score(test["survived"], classification)
MAE = mean_absolute_error(test["survived"], classification)
MSE = mean_squared_error(test["survived"], classification)

print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)


[0 1]
 ACC : 0.66
 MAE : 0.34
 MSE : 0.34


Identify the best K

In [201]:
Ks = 10
accuracy = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1, Ks):    
    KNN = KNeighborsClassifier(n_neighbors = n).fit(train[["age", "fare"]], train["survived"])  
    classification = KNN.predict(test[["age", "fare"]])
    accuracy[n - 1] = accuracy_score(test["survived"], classification)
    
print("Best  ACC : %.2f" % accuracy.max(), ", with k = ", accuracy.argmax() + 1)


Best  ACC : 0.69 , with k =  7


# Classification - Logistic Regression

Use the same process of Import all required packages and Load & profile the data with Classification - KNN Section above. With an addition of sklearn.linear_models (Logistic) and some metrics from sklearn.metrics packages

In [202]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, f1_score

Train with Logistic Regression

In [203]:
LGR = LogisticRegression(C = 0.01, solver = 'liblinear').fit(train[["age", "fare"]], train["survived"]) 

Clasify new data & evaluate the model (plus F1 and classification report)

In [204]:
newClassification = LGR.predict([[17,8],[8,10]])
print(newClassification)

classification = LGR.predict(test[["age", "fare"]])
accuracy = accuracy_score(test["survived"], classification)
MAE = mean_absolute_error(test["survived"], classification)
MSE = mean_squared_error(test["survived"], classification)
F1  = f1_score(test["survived"], classification, average='weighted') 
cnf_matrix = confusion_matrix(test["survived"], classification, labels=[0,1])


print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)
print(" F1  : %.2f" % F1)
print (classification_report(test["survived"], classification))
print(cnf_matrix)

[0 0]
 ACC : 0.65
 MAE : 0.35
 MSE : 0.35
 F1  : 0.61
              precision    recall  f1-score   support

           0       0.65      0.91      0.76       102
           1       0.67      0.26      0.38        68

    accuracy                           0.65       170
   macro avg       0.66      0.59      0.57       170
weighted avg       0.66      0.65      0.61       170

[[93  9]
 [50 18]]


Probability each class

In [205]:
classificationProb = LGR.predict_proba(test[["age", "fare"]])
print(classificationProb)

[[0.52  0.48 ]
 [0.616 0.384]
 [0.728 0.272]
 [0.689 0.311]
 [0.681 0.319]
 [0.636 0.364]
 [0.645 0.355]
 [0.627 0.373]
 [0.675 0.325]
 [0.074 0.926]
 [0.514 0.486]
 [0.534 0.466]
 [0.689 0.311]
 [0.592 0.408]
 [0.638 0.362]
 [0.69  0.31 ]
 [0.613 0.387]
 [0.641 0.359]
 [0.689 0.311]
 [0.727 0.273]
 [0.64  0.36 ]
 [0.574 0.426]
 [0.584 0.416]
 [0.652 0.348]
 [0.648 0.352]
 [0.555 0.445]
 [0.658 0.342]
 [0.704 0.296]
 [0.645 0.355]
 [0.673 0.327]
 [0.691 0.309]
 [0.474 0.526]
 [0.642 0.358]
 [0.689 0.311]
 [0.689 0.311]
 [0.506 0.494]
 [0.562 0.438]
 [0.505 0.495]
 [0.633 0.367]
 [0.635 0.365]
 [0.64  0.36 ]
 [0.579 0.421]
 [0.524 0.476]
 [0.524 0.476]
 [0.775 0.225]
 [0.673 0.327]
 [0.648 0.352]
 [0.508 0.492]
 [0.689 0.311]
 [0.577 0.423]
 [0.78  0.22 ]
 [0.751 0.249]
 [0.657 0.343]
 [0.813 0.187]
 [0.764 0.236]
 [0.494 0.506]
 [0.473 0.527]
 [0.798 0.202]
 [0.687 0.313]
 [0.689 0.311]
 [0.478 0.522]
 [0.646 0.354]
 [0.13  0.87 ]
 [0.627 0.373]
 [0.273 0.727]
 [0.679 0.321]
 [0.819 0.

# Classification - Decision Tree

Use the same process of Import all required packages and Load & profile the data with Classification - KNN Section above. With an addition of sklearn.tree (DecisionTree)

In [206]:
from sklearn.tree import DecisionTreeClassifier

Training Process

In [207]:
DST = DecisionTreeClassifier(criterion="gini", max_depth = 10).fit(train[["age", "fare"]], train["survived"]) 

Clasify new data & evaluate the model

In [208]:
newClassification = DST.predict([[17,8],[8,10]])
print(newClassification)

classification = DST.predict(test[["age", "fare"]])
accuracy = accuracy_score(test["survived"], classification)
MAE = mean_absolute_error(test["survived"], classification)
MSE = mean_squared_error(test["survived"], classification)
F1  = f1_score(test["survived"], classification, average='weighted') 
cnf_matrix = confusion_matrix(test["survived"], classification, labels=[0,1])


print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)
print(" F1  : %.2f" % F1)
print (classification_report(test["survived"], classification))
print(cnf_matrix)

[0 0]
 ACC : 0.66
 MAE : 0.34
 MSE : 0.34
 F1  : 0.63
              precision    recall  f1-score   support

           0       0.67      0.86      0.75       102
           1       0.63      0.35      0.45        68

    accuracy                           0.66       170
   macro avg       0.65      0.61      0.60       170
weighted avg       0.65      0.66      0.63       170

[[88 14]
 [44 24]]


# Classification - SVM

Use the same process of Import all required packages and Load & profile the data with Classification - KNN Section above. With an addition of sklearn.svm

In [209]:
from sklearn import svm

Training Process

In [210]:
SVM = svm.SVC(kernel='rbf', gamma='auto').fit(train[["age", "fare"]], train["survived"]) 

Clasify new data & evaluate the model

In [211]:
newClassification = SVM.predict([[17,8],[8,10]])
print(newClassification)

classification = SVM.predict(test[["age", "fare"]])
accuracy = accuracy_score(test["survived"], classification)
MAE = mean_absolute_error(test["survived"], classification)
MSE = mean_squared_error(test["survived"], classification)
F1  = f1_score(test["survived"], classification, average='weighted') 
cnf_matrix = confusion_matrix(test["survived"], classification, labels=[0,1])


print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)
print(" F1  : %.2f" % F1)
print (classification_report(test["survived"], classification))
print(cnf_matrix)

[0 0]
 ACC : 0.59
 MAE : 0.41
 MSE : 0.41
 F1  : 0.52
              precision    recall  f1-score   support

           0       0.61      0.88      0.72       102
           1       0.45      0.15      0.22        68

    accuracy                           0.59       170
   macro avg       0.53      0.51      0.47       170
weighted avg       0.55      0.59      0.52       170

[[90 12]
 [58 10]]


# Classification - Additional Material

Import required packages

In [212]:
import pandas as pd
import numpy as np
from sklearn import svm, preprocessing
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split

Pre-processing

In [213]:
dataTitanic = pd.read_csv("titanic_train.csv")

for i in dataTitanic:
  print(i, dataTitanic[i].dtypes)
  if dataTitanic[i].isna().values.any() and dataTitanic[i].dtypes != object:
      dataTitanic[i] = dataTitanic[i].fillna(dataTitanic[i].mean())



passenger_id int64
pclass int64
name object
sex object
age float64
sibsp int64
parch int64
ticket object
fare float64
cabin object
embarked object
boat object
body float64
home.dest object
survived int64


Preprocess - encode non real values

In [214]:
X = dataTitanic[["age", "fare", "sex"]].values
encode = preprocessing.LabelEncoder().fit(['male','female'])
X[:,2] = encode.transform(X[:,2]) 
Y = dataTitanic["survived"]

XTrain, XTest, YTrain, YTest = train_test_split(X,Y, test_size=0.2, random_state=3)

Clasify new data & evaluate the model - SVM

In [215]:
SVM = svm.SVC(kernel='rbf', gamma='auto').fit(XTrain, YTrain) 
newClassification = SVM.predict([[17,8,1],[8,10,0]])
print(newClassification)

classification = SVM.predict(XTest)
accuracy = accuracy_score(YTest, classification)
MAE = mean_absolute_error(YTest, classification)
MSE = mean_squared_error(YTest, classification)
F1  = f1_score(YTest, classification, average='weighted') 
cnf_matrix = confusion_matrix(YTest, classification, labels=[0,1])


print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)
print(" F1  : %.2f" % F1)
print (classification_report(YTest, classification))
print(cnf_matrix)

[0 0]
 ACC : 0.69
 MAE : 0.31
 MSE : 0.31
 F1  : 0.68
              precision    recall  f1-score   support

           0       0.74      0.84      0.79       113
           1       0.56      0.40      0.47        57

    accuracy                           0.69       170
   macro avg       0.65      0.62      0.63       170
weighted avg       0.68      0.69      0.68       170

[[95 18]
 [34 23]]


Clasify new data & evaluate the model - Decision Tree

In [216]:
DST = DecisionTreeClassifier(criterion="gini", max_depth = 10).fit(XTrain, YTrain) 
newClassification = SVM.predict([[17,8,1],[8,10,0]])
print(newClassification)

classification = DST.predict(XTest)
accuracy = accuracy_score(YTest, classification)
MAE = mean_absolute_error(YTest, classification)
MSE = mean_squared_error(YTest, classification)
F1  = f1_score(YTest, classification, average='weighted') 
cnf_matrix = confusion_matrix(YTest, classification, labels=[0,1])


print(" ACC : %.2f" % accuracy)
print(" MAE : %.2f" % MAE)
print(" MSE : %.2f" % MSE)
print(" F1  : %.2f" % F1)
print (classification_report(YTest, classification))
print(cnf_matrix)

[0 0]
 ACC : 0.79
 MAE : 0.21
 MSE : 0.21
 F1  : 0.79
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       113
           1       0.70      0.67      0.68        57

    accuracy                           0.79       170
   macro avg       0.77      0.76      0.77       170
weighted avg       0.79      0.79      0.79       170

[[97 16]
 [19 38]]
